## modify metadata objects

update.metadata <- function(m, ...){
  args <- c(as.list(environment()), list(...))
  objname <- args$m
  a <- names(args)
  
  args <- args[!a == "m"]
  a <- a[!grepl("m", a)]
  
  if(all(a %in% slotNames(m))){
    for(i in 1:length(args)){
      slot(m, a[i]) <- args[[i]] 
    }
  } else {
    wrong <- a[!(a %in% slotNames(m))]
    print(paste("Argument", wrong, "not defined in the metadata object!", sep= " "))
  }
  m
}

initialize.object <- function(type, k, distfunc, seed){
  
  cl <- paste("cl", 1:k, sep="")
  clusters <- list()
  clusters <- sapply(cl,function(x) NULL)
  clusters <- lapply(clusters, function(x) formals(distfunc))
  
  new(type, clusters=clusters, seed=seed, dist=distfunc)

}

save.setup <- function(name, type, author, mail, inst, cit = "Unpublished", objects, table, seed, ...){
	
	newname <- paste(strsplit(name, ".R")[[1]], ".R", sep="")
	funcname <- strsplit(name, ".R")[[1]]
	file.create(newname)
	
	cat("# Simulation setup file generated by \n \n", file = newname)
	cat(paste("# ", author, "\n", "# ", mail, "\n", "# ", inst, "\n \n", sep = ""), file = newname, append = T)
	
	cat(paste(funcname, " <- function(setnr = NULL, seed = NULL, info = F) { \n \n", sep=""), file=newname, append=T)
    infotable <- capture.output(dput(table))
    cat(paste("  infotable <- ", infotable[1], "\n", sep = ""), file = newname, append=T)
    cat(paste("    ", infotable[-1], "\n", sep = ""), file = newname, append=T)
    cat("\n", file = newname, append=T)
	cat(paste("  reference <- ", strsplit(capture.output(cit), "] ")[[1]][2], "\n \n", sep = ""), file = newname, append=T)
	cat(paste("  if(info == T) return(list(summary=infotable, reference=reference)) \n \n"), file = newname, append=T)
	
	objlength <- length(objects)
	
	cat("  # For a specified seed and setnr, return the respective metadata object \n \n", file = newname, append=T)
	cat("  set.seed(seed) \n \n", file = newname, append=T)
	
	for(i in 1:objlength){
	  cat(paste("  if(setnr == ",  i, ") \n \n", sep =""), file = newname, append=T)
	  cat(paste("    return(", capture.output(dput(objects[[i]]))[1], "\n", sep =""), file = newname, append = T)
	  cat(paste("    ", capture.output(dput(objects[[i]]))[-1], "\n", sep =""), file = newname, append = T)	
	  cat("    )\n", file = newname, append=T)
	}    
	cat("}", file = newname, append=T)
}
